sudo: false
dist: focal
language: node_js
node_js:
  - '24'
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - npm install -g pnpm
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script: pnpm run build
notifications:
  email: false
