import {createRequire} from 'node:module';
import * as path from 'node:path';

// Regenerates ps-pokemon.dexnums.mjs from a pokemon-showdown checkout:
//
//   node tools/spritedata/dexnums.ts ~/smogon/pokemon-showdown > ps-pokemon.dexnums.mjs
//
// The PS icon sheet puts a base species at the slot named by its dex number,
// and only alt formes need the hand-kept index table in ps-pokemon.sheet.mjs.

type PokedexEntry = {
    num: number,
    name: string,
    baseSpecies?: string
};

let ps = process.argv[2];
if (!ps) {
    throw new Error('usage: node tools/spritedata/dexnums.ts <pokemon-showdown checkout>');
}

let require = createRequire(import.meta.url);
let {Pokedex} = require(path.resolve(ps, 'dist/data/pokedex.js')) as
    {Pokedex: Record<string, PokedexEntry>};

let out = '';
out += '// Generated by tools/spritedata/dexnums.ts; do not edit.\n';
out += '// PS id of every base species -> its national dex number.\n\n';
out += 'export const DEX_NUMS = {\n';
for (let {num, name, baseSpecies} of Object.values(Pokedex)) {
    if (baseSpecies) continue;
    out += `\t${name.toLowerCase().replace(/[^a-z0-9]+/g, '')}: ${num},\n`;
}
out += '};\n';

process.stdout.write(out);
