import {encode, publishedName, smogon} from '@smogon/sprite-data/index.ts';

import {species} from './pokedex.ts';

// Regenerates data/lib/formes.ts from a pokemon-showdown checkout:
//
//   node tools/spritedata/formes.ts ~/smogon/pokemon-showdown > data/lib/formes.ts
//
// The games drew some formes no art of their own, and a set that has none
// falls back on the nearest forme it is a refinement of, up to the base
// species: PS's own icon sheet points Gourgeist-Super at Gourgeist's slot and
// Mimikyu-Busted-Totem at Mimikyu's. That chain can't be recovered from a
// published name alone, since a base name carries dashes too (kommo-o,
// mr-mime, porygon-z), so it is written down here.
//
// The parent is the longest run of leading words that names a forme of its
// own, and the base species otherwise. Dropping one word blindly would strand
// Toxtricity-Low-Key on a Toxtricity-Low that does not exist.

let ps = process.argv[2];
if (!ps) {
    throw new Error('usage: node tools/spritedata/formes.ts <pokemon-showdown checkout>');
}

// `forme` comes in encoded; `base` does not.
function published(base: string, forme: string): string {
    let extra = new Map<string, string>();
    if (forme) {
        extra.set('o', forme);
    }
    return publishedName({kind: 's', name: encode(base), extra}, smogon);
}

let all = species(ps);

// Which formes each base species actually has, so a parent can be checked.
let formes = new Map<string, Set<string>>();
for (let {base, forme} of all) {
    let set = formes.get(base);
    if (!set) {
        set = new Set();
        formes.set(base, set);
    }
    set.add(encode(forme));
}

function parent(base: string, forme: string): string {
    let words = forme.split('_');
    for (let n = words.length - 1; n > 0; n--) {
        let shorter = words.slice(0, n).join('_');
        if (formes.get(base)?.has(shorter)) {
            return shorter;
        }
    }
    return '';
}

let out = '';
out += '// Generated by tools/spritedata/formes.ts; do not edit.\n';
out += "// Each forme's published name -> the name it falls back on for art.\n\n";
out += 'export const FORME_PARENTS: Record<string, string> = {\n';

let seen = new Set<string>();
for (let {base, forme} of all) {
    if (!forme) {
        continue;
    }
    let name = published(base, encode(forme));
    // Where formeOrder gives one name to several slots, they share a parent.
    if (seen.has(name)) {
        continue;
    }
    seen.add(name);
    out += `    '${name}': '${published(base, parent(base, encode(forme)))}',\n`;
}

out += '};\n';

process.stdout.write(out);
